#!/usr/bin/env bash
# 4 bad luck, 8 is your chance

count=0
while [ $count -le 9 ];
do
	if [ $count -eq 3 ];
	then
		echo "bad luck"
	elif [ $count -eq 7 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	count=$((count + 1))
done
