#!/usr/bin/env bash
# Superstitious numbers

count=1
while [ $count -lt 21 ];
do
	case $count in
		5)
			echo "bad luck from China"
		;;
		10)
			echo "bad luck from Japan"
		;;
		18)
			echo "bad luck from Italy"
		;;
	esac
	echo $count
	count=$((count + 1))
done
